# Emplearemos una imagen de node v.16
FROM node:16

# Instalamos libvips-dev para tener compabilidad con sharp
RUN apt-get update && apt-get install libvips-dev -y

# Configuramos como argumento el modo development
ARG NODE_ENV=development

# Podremos cambiar el modo pasa la env production al ejecutar el contenedor
ENV NODE_ENV=${NODE_ENV}

# Carpeta que contendrá node_modules
WORKDIR /opt/
COPY ./package.json ./yarn.lock ./
ENV PATH /opt/node_modules/.bin:$PATH

# Configurando tiempo de espera e instalamos las dependencias
RUN yarn config set network-timeout 600000 -g && yarn install

# Creamos un directorio para nuestra app
WORKDIR /opt/app

# Copiamos el código fuente
COPY ./ .

# Construimos el proyecto strapi
RUN yarn build
# Exponemos el puerto 1337
EXPOSE 1337

#Ejecutamos yarn develop
CMD ["yarn", "develop"]